### ISSUE TITLE
Crash in tilt_stick

### ISSUE THREAD

**Issue by vladfi1** [spxtr/p3#10] opened 2016-04-21 02:59 UTC
I tried running p3 but it always immediately crashes in tilt_stick. The issue appears to be that state.players[2].cursor_y is NaN. Everything seems to work fine if I change the [2]s to [1]s - p3 (now p2) picks fox at character select and multishines in game.

**Comment by spxtr** [comment] 2016-04-22 06:38
I'm wondering if your Locations.txt isn't updated. You can get the version that should be working by calling `locations()` on the state manager, but it should update automatically. It might just be borked because your dolphin directory isn't in the same spot as mine.

**Comment by spxtr** [comment] 2016-04-22 06:39
The alternate explanation is that this stuff is working properly but dolphin is giving us NaN for some reason, which can be fixed with a wrapper to the float_handler. Can you give more details? I can't reproduce.

**Closed as completed** 2016-08-14 20:09 UTC
